name: pos_2
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  app_settings: any
  badges: any
  barcode_scan2: any
  cached_network_image: any
  change_app_package_name: any
  connectivity: any
  cron: any
  cupertino_icons: any
  date_time_picker: ^2.0.0
  dio: any
  flutter_html_to_pdf: any
  fluttertoast: any
  geolocator: 8.2.1
  get_ip_address: any
  google_fonts: any
  google_maps_flutter: any
  http: any
  image_picker: any
  material_design_icons_flutter: any
  path_provider: any
  pdf: any
  permission_handler: 9.0.2
  printing: 5.9.1
  provider: any
  qr: any
  sqflite: any
  shared_preferences: any
  search_choices: any
  share: any
  syncfusion_flutter_datepicker: any
  url_launcher: any
  video_player: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/TM Tech POS.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - i18n/
